/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.AdminstrativeRole.Supplier.AdminWorkAreaJPanel;
import UserInterface.SalesPerson.SalesPersonWorkAreaJPanel;
import UserInterface.SupplierRole.SupplierWorkAreaJPanel;
import business.configuration.Business;
import business.sales.Person;
import business.supplier.Supplier;

import java.awt.CardLayout;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sun.security.util.Password;

/**
 *
 * @author chava
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    private JPanel userprocessContainer;
    private Business business;
    private Supplier supplier;
    public LoginJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userprocessContainer=userProcessContainer;
        this.business=business;
       // lblCompanyName.setText(business.getBusinessName());
     removeValues(); 
    }
     public void removeValues(){
         
         
        txtFieldUserName.setText("");
        passwordFieldLogin.setText("");
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passwordFieldLogin = new javax.swing.JPasswordField();
        lblCompanyName = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel2.setText("Password  :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        txtFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUserNameActionPerformed(evt);
            }
        });
        add(txtFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, 30));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("LOGIN ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        add(passwordFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, 33));

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 280, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String userName = txtFieldUserName.getText();
            String password = (passwordFieldLogin.getText());
            
            if(userName.equalsIgnoreCase("")){
                
                JOptionPane.showMessageDialog(null, "Please enter User Name");
            }
            else if (password.equalsIgnoreCase("")){
                
                JOptionPane.showMessageDialog(null, "Please enter password");
            }
            
            else{
            Supplier supplier= business.getSupplierDirectory().validateUser(userName, password);
           Person person= business.getEmployeeDirectory().validateUser(userName, password);
           if(person!=null){     
          // for(Person person :business.getEmployeeDirectory().getPersonList()){
                    if(person.getUserName().equalsIgnoreCase(userName)){
                    //System.out.print("HI "+ usrAccount.getUserName()+" "+usrAccount.getRole()+" \n");
                    if(person.getRole().equalsIgnoreCase("Admin")){
                        
                 
                    AdminWorkAreaJPanel panel = new AdminWorkAreaJPanel(userprocessContainer,business);
                    userprocessContainer.add("AdminWorkJPanel", panel);
                    CardLayout layout = (CardLayout) userprocessContainer.getLayout();
                    layout.next(userprocessContainer);
                    
                    }
                    
                    else if(person.getRole().equalsIgnoreCase("Sales"))
                    {
                        
                    SalesPersonWorkAreaJPanel panel = new SalesPersonWorkAreaJPanel(userprocessContainer,business,person);
                    userprocessContainer.add("SalesPersonWorkAreaJPanel", panel);
                    CardLayout layout = (CardLayout) userprocessContainer.getLayout();
                    layout.next(userprocessContainer);                        
                        
                    }
                   
         }
            }
           else if(supplier!=null){
               SupplierWorkAreaJPanel panel = new SupplierWorkAreaJPanel(userprocessContainer,supplier);
                    userprocessContainer.add("SupplierWorkAreaJPanel", panel);
                    CardLayout layout = (CardLayout) userprocessContainer.getLayout();
                    layout.next(userprocessContainer);
           }
            else {
                JOptionPane.showMessageDialog(null, "User doesn't Exists");
            }
        }
        txtFieldUserName.setText("");
        passwordFieldLogin.setText("");
    }       
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Account is Disabled / Deleted Please contact the administrator");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JPasswordField passwordFieldLogin;
    private javax.swing.JTextField txtFieldUserName;
    // End of variables declaration//GEN-END:variables
}
