/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import UserInterface.LoginJPanel;
import business.configuration.Business;
import business.sales.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Person person;
    public SalesPersonWorkAreaJPanel(JPanel userprocessContainer, Business business,Person person) {
        initComponents();
        this.userProcessContainer=userprocessContainer;
        this.business = business;
        this.person=person;
        
        txtFieldEmployeeId.setText(person.getEmployeeId());
        txtFieldSalesPersonName.setText(person.getName());
        txtFieldEmployeeId.setEnabled(false);
        txtFieldSalesPersonName.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCustomers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldEmployeeId = new javax.swing.JTextField();
        txtFieldSalesPersonName = new javax.swing.JTextField();
        btnReviewSalesOrderHistory = new javax.swing.JButton();
        btnReviewSalesCommission = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });
        add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 250, -1));

        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("Employee Id: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtFieldEmployeeId.setEditable(false);
        add(txtFieldEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        txtFieldSalesPersonName.setEditable(false);
        add(txtFieldSalesPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        btnReviewSalesOrderHistory.setText("Review Sales Order History");
        btnReviewSalesOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewSalesOrderHistoryActionPerformed(evt);
            }
        });
        add(btnReviewSalesOrderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 250, -1));

        btnReviewSalesCommission.setText("Review Sales Commission");
        btnReviewSalesCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewSalesCommissionActionPerformed(evt);
            }
        });
        add(btnReviewSalesCommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 250, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
        
                    ManageCustJPanel panel = new ManageCustJPanel(userProcessContainer,business,person);
                    userProcessContainer.add("ManageCustomersJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnReviewSalesOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewSalesOrderHistoryActionPerformed
        // TODO add your handling code here:
        
        ReviewSalesOrderJPanel panel = new ReviewSalesOrderJPanel(userProcessContainer,business,person);
        userProcessContainer.add("ReviewSalesOrderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewSalesOrderHistoryActionPerformed

    private void btnReviewSalesCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewSalesCommissionActionPerformed
        // TODO add your handling code here:
        
        ReviewCommissionJPanel panel = new ReviewCommissionJPanel(userProcessContainer,business,person);
        userProcessContainer.add("ReviewCommissionJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewSalesCommissionActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        JOptionPane.showMessageDialog(null, "Logged out Successfully");

    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnReviewSalesCommission;
    private javax.swing.JButton btnReviewSalesOrderHistory;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFieldEmployeeId;
    private javax.swing.JTextField txtFieldSalesPersonName;
    // End of variables declaration//GEN-END:variables
}
