/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import business.configuration.Business;
import business.market.Customer;
import business.market.MarketOfferCatalog;
import business.sales.Person;
import business.supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class ServeCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServerCustomerJPanel
     */
    private Business business;
    private JPanel userProcessContainer;
    private MarketOfferCatalog marketOfferCatalog;
    private Customer customer;
    private Person person;
    private SupplierDirectory supplierDirectory;
    public ServeCustomerJPanel(JPanel userProcessContainer, Business business,Customer customer,Person person) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        this.marketOfferCatalog=business.getMarketOfferCatalog();
        this.customer=customer;
        this.person = person;
        this.supplierDirectory = business.getSupplierDirectory();
        
        lblCustomerName.setText(customer.getName());
        lblUserName.setText("User: "+person.getName());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        btnBookCustomerOrder = new javax.swing.JButton();
        btnCheckOrderStatus = new javax.swing.JButton();
        btnViewCustomerHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("SERVE CUSTOMER");

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("jLabel1");

        jLabel3.setText("Customer Name:");

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCustomerName.setText("jLabel4");

        btnBookCustomerOrder.setText("Book Customer Order");
        btnBookCustomerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookCustomerOrderActionPerformed(evt);
            }
        });

        btnCheckOrderStatus.setText("Check Order Status");
        btnCheckOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOrderStatusActionPerformed(evt);
            }
        });

        btnViewCustomerHistory.setText("View Order History");
        btnViewCustomerHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerHistoryActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addComponent(lblUserName)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerName))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewCustomerHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBookCustomerOrder)
                        .addGap(22, 22, 22)
                        .addComponent(btnCheckOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookCustomerOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCustomerHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(486, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookCustomerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookCustomerOrderActionPerformed
        // TODO add your handling code here:
        
        BrowseProductJPanel panel=new BrowseProductJPanel(userProcessContainer,business,customer,person);
        userProcessContainer.add("BrowseProductJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnBookCustomerOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewCustomerHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerHistoryActionPerformed
        // TODO add your handling code here:
        
        CustomerSalesHistoryJPanel panel = new CustomerSalesHistoryJPanel(userProcessContainer,business,customer,person);
        userProcessContainer.add("CustomerSalesHistoryJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnViewCustomerHistoryActionPerformed

    private void btnCheckOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOrderStatusActionPerformed
        // TODO add your handling code here:
        
    CheckStatusJPanel panel = new CheckStatusJPanel(userProcessContainer,business,customer,person);
    userProcessContainer.add("CheckStatusJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);        
        
    }//GEN-LAST:event_btnCheckOrderStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookCustomerOrder;
    private javax.swing.JButton btnCheckOrderStatus;
    private javax.swing.JButton btnViewCustomerHistory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
