/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirplaneCatalog;
import Business.CustomerCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class ManageCustomers extends javax.swing.JPanel {
  private JPanel userConrtolDisplayPanel;
  private CustomerCatalog cCatalog;
  private AirplaneCatalog aCatalog;
  
    /**
     * Creates new form ManageCustomers
     */
    

    ManageCustomers(JPanel userControlDisplayPanel, AirplaneCatalog aCatalog) {
    initComponents();
    this.userConrtolDisplayPanel=userControlDisplayPanel;
    this.aCatalog=aCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCheapestFlights = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE CUSTOMERS");

        btnCheapestFlights.setText("Search For Cheapest Flights");
        btnCheapestFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheapestFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnCheapestFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheapestFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheapestFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheapestFlightsActionPerformed
    CheapestFlights panel=new CheapestFlights(userConrtolDisplayPanel,aCatalog);
    userConrtolDisplayPanel.add("ManageAirliner",panel);
    CardLayout layout=(CardLayout)userConrtolDisplayPanel.getLayout();
    layout.next(userConrtolDisplayPanel);
    
    }//GEN-LAST:event_btnCheapestFlightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheapestFlights;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

