/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole.MonitorSales;

import UserInterface.AdminstrativeRole.Person.ManagePersonDirectoryJPanel;
import business.configuration.Business;
import business.supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class MonitorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitorWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private Business business;
    public MonitorWorkAreaJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton2 = new javax.swing.JButton();
        btnMonitor = new javax.swing.JButton();
        btnSalesPerson = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("MONITOR SALES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, 40));

        backjButton2.setText("Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 30));

        btnMonitor.setText("Monitor Sales Performance");
        btnMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorActionPerformed(evt);
            }
        });
        add(btnMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 230, -1));

        btnSalesPerson.setText("Monitor Sales Person Performance");
        btnSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesPersonActionPerformed(evt);
            }
        });
        add(btnSalesPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btnProducts.setText("Top Products");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void btnMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorActionPerformed
        // TODO add your handling code here:
         SalesPerformanceJPanel panel = new SalesPerformanceJPanel(userProcessContainer, business);
        userProcessContainer.add("SalesPerformanceJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMonitorActionPerformed

    private void btnSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesPersonActionPerformed
        // TODO add your handling code here:
        SalesPersonPerformanceJPanel panel = new SalesPersonPerformanceJPanel(userProcessContainer, business);
        userProcessContainer.add("SalesPersonPerformanceJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSalesPersonActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        // TODO add your handling code here:
        
        TopProductsJPanel panel = new TopProductsJPanel(userProcessContainer, business);
        userProcessContainer.add("TopProductsJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton btnMonitor;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnSalesPerson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
