/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole.MonitorSales;

import business.configuration.Business;
import business.market.Market;
import business.market.MarketOffer;
import business.sales.Order;
import business.sales.OrderItem;
import business.supplier.Product;
import business.supplier.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class SalesPerformanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPerformanceJPanel
     */
    
     private JPanel userProcessContainer;
    private Business business;
    
    public SalesPerformanceJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        for (Market market : business.getMarketDirectory().getMarketList()) {
            comboMarket.addItem(market);
        }
        populateXeroxValues();
        populateMarketValues();
    }
    public void populateXeroxValues(){
         //Code for actual price
        double total=0;
        for (Order order : business.getOrderDirectory().getOrderList()) {
            total= total+order.orderTotal();
        }
        txtXeroxTotal.setText(String.valueOf(total));
        
        //Code for targetted price
        double targetTotal=0;
        for (Order order : business.getOrderDirectory().getOrderList()) {
            for (OrderItem orderItem : order.getOrderItemList()) {
                MarketOffer offer= orderItem.getMarketOffer();
                    targetTotal = targetTotal + (offer.getProduct().getPrice()* offer.getTargetRatio()* orderItem.getQuantity());       
            }
            
        }
        txtXeroxTarget.setText(String.valueOf(targetTotal));  
        
        double profit= targetTotal-total;
        
        txtXeroxProfit.setText(String.valueOf(profit));
    }
    
   public void populateMarketValues(){
       Market m= (Market)comboMarket.getSelectedItem();
         double total=0;
        for (Order order : business.getOrderDirectory().getOrderList()) {
            for (OrderItem orderItem : order.getOrderItemList()) {
                Market mar= orderItem.getMarketOffer().getMarket();
                if(mar.getMarketId().equals(m.getMarketId())){
                    
                  total=total+order.orderTotal();
                //total= total+ (orderItem.getQuantity()* orderItem.getMarketOffer().getTargetRatio() * orderItem.getMarketOffer().getProduct().getPrice());
                } 
            } 
           // total= total+order.orderTotal();
        }
        txtMarketTotal.setText(String.valueOf(total));
        
        //Code for targetted price
        double targetTotal=0;
        for (Order order : business.getOrderDirectory().getOrderList()) {
            for (OrderItem orderItem : order.getOrderItemList()) {
                MarketOffer offer= orderItem.getMarketOffer();
                if(offer.getMarket().getMarketId().equals(m.getMarketId())){
                    targetTotal = targetTotal + (offer.getProduct().getPrice()* offer.getTargetRatio()* orderItem.getQuantity());       
            }
            }
            
        }
        txtMarketTarget.setText(String.valueOf(targetTotal));  
        double profit= targetTotal-total;
        txtMarketProfit.setText(String.valueOf(profit));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtXeroxTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtXeroxTarget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtXeroxProfit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backjButton2 = new javax.swing.JButton();
        comboMarket = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMarketTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMarketTarget = new javax.swing.JTextField();
        txtMarketProfit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Total Revenue of Xerox :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        txtXeroxTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtXeroxTotal.setEnabled(false);
        add(txtXeroxTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 210, -1));

        jLabel6.setText("Total Revenue of Xerox (Target) :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        txtXeroxTarget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtXeroxTarget.setEnabled(false);
        add(txtXeroxTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, -1));

        jLabel7.setText("Market Type :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        txtXeroxProfit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtXeroxProfit.setEnabled(false);
        add(txtXeroxProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("SALES PERFORMANCE BASED ON MARKET");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 340, 30));

        backjButton2.setText("Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 90, 30));

        comboMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarketActionPerformed(evt);
            }
        });
        add(comboMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, 30));

        jLabel8.setText("Total Profit of Xerox  :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        jLabel9.setText("Total Revenue :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 30));

        txtMarketTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMarketTotal.setEnabled(false);
        add(txtMarketTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 210, -1));

        jLabel10.setText("Total Revenue (Target) :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 30));

        txtMarketTarget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMarketTarget.setEnabled(false);
        add(txtMarketTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 210, -1));

        txtMarketProfit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMarketProfit.setEnabled(false);
        add(txtMarketProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 210, -1));

        jLabel11.setText("Total Profit :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("MONITOR SALES PERFORMANCE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 330, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void comboMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarketActionPerformed
        // TODO add your handling code here:
        populateMarketValues();
    }//GEN-LAST:event_comboMarketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JComboBox comboMarket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMarketProfit;
    private javax.swing.JTextField txtMarketTarget;
    private javax.swing.JTextField txtMarketTotal;
    private javax.swing.JTextField txtXeroxProfit;
    private javax.swing.JTextField txtXeroxTarget;
    private javax.swing.JTextField txtXeroxTotal;
    // End of variables declaration//GEN-END:variables
}
