/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole.MarketOffer;

import business.configuration.Business;
import business.market.Market;
import business.market.MarketOffer;
import business.supplier.Product;
import business.supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class CreateMarketOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMarketOfferJPanel
     */
    JPanel userProcessContainer;
    Business business;
    MarketOffer offer;
    public CreateMarketOfferJPanel(JPanel userProcessContainer, Business business ) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        for (Market market : business.getMarketDirectory().getMarketList()) {
            comboMarket.addItem(market);
        }
         for (Supplier supplier : business.getSupplierDirectory().getSupplierDict()) {
            comboSupplier.addItem(supplier);
        }
         populateProductCombo();
    }
    public void populateProductCombo(){
        comboProduct.removeAllItems();
         Supplier s=(Supplier)comboSupplier.getSelectedItem();
        for (Product product : s.getProductCatalog().getProductCatalog()) {
            comboProduct.addItem(product);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCeil = new javax.swing.JTextField();
        comboMarket = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtTarget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFloor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboSupplier = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboProduct = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("CREATE MARKET OFFER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 230, 30));

        jLabel3.setText("Market Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel4.setText("Ceiling Price: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        txtCeil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCeilKeyPressed(evt);
            }
        });
        add(txtCeil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, -1));

        add(comboMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 170, -1));

        jLabel5.setText("Target Price :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        txtTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTargetKeyPressed(evt);
            }
        });
        add(txtTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 170, -1));

        jLabel7.setText("Floor Price :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtFloor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFloorKeyPressed(evt);
            }
        });
        add(txtFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 170, -1));

        jLabel8.setText("Supplier Name :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        comboSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupplierActionPerformed(evt);
            }
        });
        add(comboSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 170, -1));

        jLabel9.setText("Product:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        add(comboProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        try{
            if(!txtCeil.getText().isEmpty() && !txtFloor.getText().isEmpty() && !txtTarget.getText().isEmpty()){
                Market market=(Market) comboMarket.getSelectedItem();
                Product p =(Product) comboProduct.getSelectedItem();
               
               double ceil=Double.parseDouble(txtCeil.getText());
               double floor=Double.parseDouble(txtFloor.getText());
               double target=Double.parseDouble(txtTarget.getText());
               if(ceil>=target && target>=floor){
                   MarketOffer mOffer= business.getMarketOfferCatalog().addMarketOffer();
               mOffer.setMarket(market);
               mOffer.setProduct(p);
               mOffer.setCeilingRatio(ceil);
               mOffer.setFloorRatio(floor);
               mOffer.setTargetRatio(target);
               JOptionPane.showMessageDialog(null, "Market Offer created successfully");
               }
               else{
                   JOptionPane.showMessageDialog(null, "Enter ratio ceil >= target >= Floor ");
               }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter all values");
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter float for ceil, floor and Target", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MarketOfferJPanel jPanel = (MarketOfferJPanel) component;
        jPanel.populateMarketOffer();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCeilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCeilKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCeilKeyPressed

    private void txtTargetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTargetKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetKeyPressed

    private void txtFloorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFloorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFloorKeyPressed

    private void comboSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupplierActionPerformed
        // TODO add your handling code here:
        comboProduct.removeAllItems();
       populateProductCombo();
    }//GEN-LAST:event_comboSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox comboMarket;
    private javax.swing.JComboBox comboProduct;
    private javax.swing.JComboBox comboSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCeil;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
