/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole.MarketOffer;

import business.configuration.Business;
import business.market.MarketOffer;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chava
 */
public class UpdateMarketOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMarketOfferJPanel
     */
    JPanel userProcessContainer;
    Business business;
    MarketOffer offer;
    public UpdateMarketOfferJPanel(JPanel userProcessContainer,Business business,MarketOffer market) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.offer=market;
        populateValues();
       
        
    }
public void populateValues(){
     txtCeil.setText(String.valueOf(offer.getCeilingRatio()));
        txtFloor.setText(String.valueOf(offer.getFloorRatio()));
        txtTarget.setText(String.valueOf(offer.getTargetRatio()));
        txtProduct.setText(offer.getProduct().getProdName());
        txtMarketName.setText(offer.getMarket().getMarketName());
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCeil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTarget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFloor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMarketName = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("UPDATE MARKET OFFER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 230, 30));

        jLabel3.setText("Market Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel4.setText("Ceiling Price: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        txtCeil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCeilKeyPressed(evt);
            }
        });
        add(txtCeil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 170, -1));

        jLabel5.setText("Target Price :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTargetKeyPressed(evt);
            }
        });
        add(txtTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, -1));

        jLabel7.setText("Floor Price :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtFloor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFloorKeyPressed(evt);
            }
        });
        add(txtFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        jLabel9.setText("Product:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtMarketName.setEnabled(false);
        add(txtMarketName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, -1));

        txtProduct.setEnabled(false);
        add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            if(!txtCeil.getText().isEmpty() && !txtFloor.getText().isEmpty() && !txtTarget.getText().isEmpty()){
               
               double ceil=Double.parseDouble(txtCeil.getText());
               double floor=Double.parseDouble(txtFloor.getText());
               double target=Double.parseDouble(txtTarget.getText());
               if(ceil>=target && target>=floor){
               offer.setCeilingRatio(ceil);
               offer.setFloorRatio(floor);
               offer.setTargetRatio(target);
                JOptionPane.showMessageDialog(null, "Market Offer created successfully");
               }
               else{
                   JOptionPane.showMessageDialog(null, "Enter ratio ceil >= target >= Floor ");
               }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter all values");
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter float for ceil, floor and Target", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MarketOfferJPanel jPanel = (MarketOfferJPanel) component;
        jPanel.populateMarketOffer();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCeilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCeilKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCeilKeyPressed

    private void txtTargetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTargetKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetKeyPressed

    private void txtFloorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFloorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFloorKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCeil;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtMarketName;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
